name: Feature request
description: Suggest an improvement or new feature
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What do you want to see?
      description: Describe the feature and why it matters.
      placeholder: Clear and concise description
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: How would you like it to work?
  - type: textarea
    attributes:
      label: Alternatives considered
      description: Any other approaches you considered.
